### ISSUE TITLE
Error in travis build log for limit test

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#128]
This happens only once and cannot be reproduce. Need more investigation...

```
02:51:28.407 [main]       INFO  com.networknt.limit.LimitHandlerTest - starting server
02:51:28.889 [main]       INFO  com.networknt.config.Config - daily config cache refresh
02:51:28.901 [main]       INFO  com.networknt.config.Config - Unable to load config from externalized folder for limit.yml in 
02:51:28.901 [main]       INFO  com.networknt.config.Config - Trying to load config from classpath directory for file limit.yml
02:51:28.903 [main]       INFO  com.networknt.config.Config - Config loaded from default folder for limit.yml
Running com.networknt.limit.LimitHandlerTest
02:51:29.209 [main]       INFO  com.networknt.config.Config - Unable to load config from externalized folder for client.yml in 
02:51:29.210 [main]       INFO  com.networknt.config.Config - Trying to load config from classpath directory for file client.yml
02:51:29.210 [main]       INFO  com.networknt.config.Config - Config loaded from default folder for client.yml
02:51:29.226 [main]       INFO  com.networknt.config.Config - Unable to load config from externalized folder for client.yml in 
02:51:29.227 [main]       INFO  com.networknt.config.Config - Trying to load config from classpath directory for file client.yml
02:51:29.228 [main]       INFO  com.networknt.config.Config - Config loaded from default folder for client.yml
02:51:29.235 [main]       INFO  com.networknt.config.Config - Unable to load config from externalized folder for secret.yml in 
02:51:29.236 [main]       INFO  com.networknt.config.Config - Trying to load config from classpath directory for file secret.yml
02:51:29.237 [main]       INFO  com.networknt.config.Config - Config loaded from default folder for secret.yml
02:51:29.299 [main]       INFO  com.networknt.client.Http2Client - Loading trust store from config at tls/client.truststore
02:51:29.300 [main]       INFO  com.networknt.config.Config - Unable to load config from externalized folder for tls/client.truststore in 
02:51:29.300 [main]       INFO  com.networknt.config.Config - Trying to load config from classpath directory for file tls/client.truststore
02:51:29.301 [main]       INFO  com.networknt.config.Config - Config loaded from default folder for tls/client.truststore
java.nio.channels.ClosedChannelException
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:98)
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:90)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1045)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:959)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener$1.run(AbstractFramedChannel.java:971)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:919)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:913)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.NioHandle$1.run(NioHandle.java:50)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
02:51:29.967 [main]       INFO  com.networknt.limit.LimitHandlerTest - The server is stopped.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.766 sec <<< FAILURE! - in com.networknt.limit.LimitHandlerTest
testOneRequest(com.networknt.limit.LimitHandlerTest)  Time elapsed: 0.662 sec  <<< ERROR!
java.lang.NullPointerException
	at com.networknt.limit.LimitHandlerTest.testOneRequest(LimitHandlerTest.java:118)


Results :

Tests in error: 
  LimitHandlerTest.testOneRequest:118 NullPointer

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by stevehu** [comment]
The root cause maybe due to single thread execution on travis as the test is for multiple threads.
