### ISSUE TITLE
jdk 11 httpclient cannot set header for Host and Connection

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#1394]
When using the external service handle to call other services outside of the corporate network, we are using httpclient to support the proxy host and proxy port settings. However, we cannot set headers for Host and Connection. 

Here is the stacktrace output at the trace level. 

```
2022-10-07T11:49:01.680 [XNIO-1 task-1]  ePzfBceGQEeoi7pKysFyLg TRACE c.n.proxy.ExternalServiceHandler:217 copyHeaders - Ignore the exception:
java.lang.IllegalArgumentException: restricted header name: "Connection"
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Utils.java:256)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkNameAndValue(HttpRequestBuilderImpl.java:110)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.setHeader(HttpRequestBuilderImpl.java:119)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.setHeader(HttpRequestBuilderImpl.java:43)
	at com.networknt.proxy.ExternalServiceHandler.copyHeaders(ExternalServiceHandler.java:213)
	at com.networknt.proxy.ExternalServiceHandler.handleRequest(ExternalServiceHandler.java:125)
	at com.networknt.handler.Handler.next(Handler.java:212)
	at com.networknt.handler.Handler.next(Handler.java:233)
	at com.networknt.audit.AuditHandler.next(AuditHandler.java:197)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:186)
	at com.networknt.handler.Handler.next(Handler.java:212)
	at com.networknt.handler.Handler.next(Handler.java:233)
	at com.networknt.handler.ResponseInterceptorInjectionHandler.handleRequest(ResponseInterceptorInjectionHandler.java:137)
	at com.networknt.handler.Handler.next(Handler.java:231)
	at com.networknt.handler.RequestInterceptorInjectionHandler.handleRequest(RequestInterceptorInjectionHandler.java:140)
	at com.networknt.handler.Handler.next(Handler.java:212)
	at com.networknt.handler.Handler.next(Handler.java:233)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:77)
	at com.networknt.handler.Handler.next(Handler.java:212)
	at com.networknt.handler.Handler.next(Handler.java:233)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:68)
	at com.networknt.handler.Handler.next(Handler.java:212)
	at com.networknt.handler.Handler.next(Handler.java:233)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:76)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by stevehu** [comment]
After searching on the Internet, it looks like we cannot do that with Java 11. Java 12 has system properties to enable the Host and Connection header, as described in the following link. I also tested on the JDK 11 and confirmed that it is not working. 

https://stackoverflow.com/questions/52315472/how-to-customise-host-header-in-java-http-client
