### ISSUE TITLE
Response interceptor for chunked responses larger than default server buffer not working with SSL requests

### ISSUE THREAD

**Issue by DiogoFKT** [networknt/light-4j#1398]
When large response payloads requires server buffer to be increased the response interceptor configured works fine and can properly transform the payload however it will throw IO exception from SslConduit - perhaps because its buffer is not in sync

stack trace below

_22:09:13.959 [XNIO-1 I/O-3]   DEBUG i.u.c.ChunkedStreamSinkConduit:304 terminateWrites - Channel closed mid-chunk
22:09:13.963 [XNIO-1 I/O-3]   ERROR c.n.h.ProxyHandler$HTTPTrailerChannelListener:796 handleEvent - IOException:
java.nio.channels.AsynchronousCloseException: null
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:153)
        at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:947)
        at io.undertow.protocols.ssl.SslConduit.write(SslConduit.java:389)
        at io.undertow.server.protocol.http.HttpResponseConduit.write(HttpResponseConduit.java:614)
        at io.undertow.conduits.ChunkedStreamSinkConduit.flush(ChunkedStreamSinkConduit.java:270)
        at org.xnio.conduits.AbstractSinkConduit.flush(AbstractSinkConduit.java:86)
        at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
        at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
        at com.networknt.handler.ProxyHandler$HTTPTrailerChannelListener.handleEvent(ProxyHandler.java:782)
        at com.networknt.handler.ProxyHandler$HTTPTrailerChannelListener.handleEvent(ProxyHandler.java:758)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65)
        at io.undertow.protocols.ssl.SslConduit$SslWriteReadyHandler.writeReady(SslConduit.java:1351)
        at io.undertow.protocols.ssl.SslConduit$4.run(SslConduit.java:448)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
22:09:13.964 [XNIO-1 I/O-3]   ERROR com.networknt.handler.ProxyHandler:685 handleFailure - UT005028: Proxy request to /MemberWS/web failed
java.nio.channels.AsynchronousCloseException: null
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:153)
        at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:947)
        at io.undertow.protocols.ssl.SslConduit.write(SslConduit.java:389)
        at io.undertow.server.protocol.http.HttpResponseConduit.write(HttpResponseConduit.java:614)
        at io.undertow.conduits.ChunkedStreamSinkConduit.flush(ChunkedStreamSinkConduit.java:270)
        at org.xnio.conduits.AbstractSinkConduit.flush(AbstractSinkConduit.java:86)
        at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
        at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
        at com.networknt.handler.ProxyHandler$HTTPTrailerChannelListener.handleEvent(ProxyHandler.java:782)
        at com.networknt.handler.ProxyHandler$HTTPTrailerChannelListener.handleEvent(ProxyHandler.java:758)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65)
        at io.undertow.protocols.ssl.SslConduit$SslWriteReadyHandler.writeReady(SslConduit.java:1351)
        at io.undertow.protocols.ssl.SslConduit$4.run(SslConduit.java:448)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

**Comment by KalevGonvick** [comment]
This issue can be resolved by enabling http2 on the server. 

The way undertow handles chunked encoding with HTTP 1/1 seems to be the root cause (ChunkedStreamConduit). Since there is currently no known use case where response transformation is required on HTTP 1/1 only, I am closing this issue.

I will re-open if there is need in the future.
