### ISSUE TITLE
We might have a multiple threading issue in the LoadBalancingRouterProxyClient

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#1607]
Under very limited CPU and memory conditions, we have received reports from our users with 503 responses instead of timeout. One of the users has captured the following stacktrace that can help us to analyze the code to pinpoint the root cause. The same issue cannot be reproduced on our side so far. 

```
2023-01-31T21:23:13.886 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:96 discovery - protocol = https serviceId = petstore tag = null
2023-01-31T21:23:13.887 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:101 discovery - subscribeUrl = https://localhost:443/petstore?group=default
2023-01-31T21:23:13.890 [XNIO-1 I/O-4]   INFO  c.n.r.support.AbstractRegistry:103 subscribe - [DirectRegistry] Listener (null) will subscribe to url (https://localhost:443/petstore?group=default) in Registry [https://localhost:8080/default/direct/1.0/service]
2023-01-31T21:23:13.892 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:106 discovery - discovered urls = [https://localhost:9443/null?group=default]
2023-01-31T21:23:13.892 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:85 services - The serviceId cannot be blank
2023-01-31T21:23:13.893 [XNIO-1 I/O-4]   ERROR i.u.s.h.p.LoadBalancingRouterProxyClient:207 getConnection - Failed to get connection
com.networknt.config.ConfigException: HostArray is empty. serviceUrl = null serviceId = null envTag = null
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.selectHost(LoadBalancingRouterProxyClient.java:269)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:198)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:250)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
2023-01-31T21:23:13.893 [XNIO-1 I/O-4]   DEBUG c.n.h.ProxyHandler$ProxyClientHandler:263 failed - Failed calling backend with tries = 0 maxRetryAttempts = 3
2023-01-31T21:23:13.895 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:278 failed - Retry target = io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient$1@1cced616
2023-01-31T21:23:13.896 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:284 failed - Retry with remaining = 199510
2023-01-31T21:23:13.897 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:85 services - The serviceId cannot be blank
2023-01-31T21:23:13.902 [XNIO-1 I/O-4]   ERROR i.u.s.h.p.LoadBalancingRouterProxyClient:207 getConnection - Failed to get connection
com.networknt.config.ConfigException: HostArray is empty. serviceUrl = null serviceId = null envTag = null
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.selectHost(LoadBalancingRouterProxyClient.java:269)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:195)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:250)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
2023-01-31T21:23:13.902 [XNIO-1 I/O-4]   DEBUG c.n.h.ProxyHandler$ProxyClientHandler:263 failed - Failed calling backend with tries = 1 maxRetryAttempts = 3
2023-01-31T21:23:13.902 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:278 failed - Retry target = io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient$1@1cced616
2023-01-31T21:23:13.902 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:284 failed - Retry with remaining = 199503
2023-01-31T21:23:13.902 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:85 services - The serviceId cannot be blank
2023-01-31T21:23:13.903 [XNIO-1 I/O-4]   ERROR i.u.s.h.p.LoadBalancingRouterProxyClient:207 getConnection - Failed to get connection
com.networknt.config.ConfigException: HostArray is empty. serviceUrl = null serviceId = null envTag = null
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.selectHost(LoadBalancingRouterProxyClient.java:269)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:195)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:250)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
2023-01-31T21:23:13.904 [XNIO-1 I/O-4]   DEBUG c.n.h.ProxyHandler$ProxyClientHandler:263 failed - Failed calling backend with tries = 2 maxRetryAttempts = 3
2023-01-31T21:23:13.904 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:278 failed - Retry target = io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient$1@1cced616
2023-01-31T21:23:13.904 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:284 failed - Retry with remaining = 199501
2023-01-31T21:23:13.904 [XNIO-1 I/O-4]   DEBUG com.networknt.cluster.LightCluster:85 services - The serviceId cannot be blank
2023-01-31T21:23:13.904 [XNIO-1 I/O-4]   ERROR i.u.s.h.p.LoadBalancingRouterProxyClient:207 getConnection - Failed to get connection
com.networknt.config.ConfigException: HostArray is empty. serviceUrl = null serviceId = null envTag = null
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.selectHost(LoadBalancingRouterProxyClient.java:269)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:195)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.failed(ProxyHandler.java:286)
	at io.undertow.server.handlers.proxy.LoadBalancingRouterProxyClient.getConnection(LoadBalancingRouterProxyClient.java:209)
	at com.networknt.handler.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:250)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
2023-01-31T21:23:13.905 [XNIO-1 I/O-4]   DEBUG c.n.h.ProxyHandler$ProxyClientHandler:263 failed - Failed calling backend with tries = 3 maxRetryAttempts = 3
2023-01-31T21:23:13.905 [XNIO-1 I/O-4]   TRACE c.n.h.ProxyHandler$ProxyClientHandler:297 failed - Max number fo retry attempts reached.
2023-01-31T21:23:13.905 [XNIO-1 I/O-4]   DEBUG c.n.h.c.ContentStreamSinkConduit:39 <init> - Executing interceptor class com.networknt.body.ResponseBodyInterceptor
2023-01-31T21:23:13.906 [XNIO-1 I/O-4]   DEBUG c.n.body.ResponseBodyInterceptor:74 handleRequest - ResponseBodyInterceptor.handleRequest starts.
2023-01-31T21:23:13.906 [XNIO-1 I/O-4]   DEBUG c.n.body.ResponseBodyInterceptor:84 handleRequest - ResponseBodyInterceptor.handleRequest ends.
2023-01-31T21:23:14.962 [XNIO-1 I/O-4]   DEBUG c.n.exception.ExceptionHandler:66 handleRequest - ExceptionHandler.handleRequest starts.

```

**Comment by stevehu** [comment]
This issue is fixed with the following PR. 

https://github.com/networknt/light-4j/pull/1618
