### ISSUE TITLE
Timeout when looking up from consul with ecwid client

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#19]
```
02:17:08.977 [Thread-5]  INFO  com.networknt.consul.ConsulRegistry - command data not change: serviceName=com.networknt.apic-1.0.0, command=: 
02:17:13.023 [Thread-2]  ERROR com.networknt.consul.ConsulRegistry - service lookup thread fail!
com.ecwid.consul.transport.TransportException: java.net.SocketTimeoutException: Read timed out
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:96)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:55)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:99)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:80)
	at com.ecwid.consul.v1.ConsulClient.getHealthServices(ConsulClient.java:399)
	at com.networknt.consul.client.ConsulEcwidClient.lookupHealthService(ConsulEcwidClient.java:61)
	at com.networknt.consul.ConsulRegistry.lookupConsulService(ConsulRegistry.java:256)
	at com.networknt.consul.ConsulRegistry.lookupServiceUpdate(ConsulRegistry.java:214)
	at com.networknt.consul.ConsulRegistry.access$200(ConsulRegistry.java:20)
	at com.networknt.consul.ConsulRegistry$ServiceLookupThread.run(ConsulRegistry.java:334)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80)
	... 10 common frames omitted
02:17:13.139 [Thread-4]  ERROR com.networknt.consul.ConsulRegistry - service lookup thread fail!
com.ecwid.consul.transport.TransportException: java.net.SocketTimeoutException: Read timed out
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:96)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:55)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:99)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:80)
	at com.ecwid.consul.v1.ConsulClient.getHealthServices(ConsulClient.java:399)
	at com.networknt.consul.client.ConsulEcwidClient.lookupHealthService(ConsulEcwidClient.java:61)
	at com.networknt.consul.ConsulRegistry.lookupConsulService(ConsulRegistry.java:256)
	at com.networknt.consul.ConsulRegistry.lookupServiceUpdate(ConsulRegistry.java:214)
	at com.networknt.consul.ConsulRegistry.access$200(ConsulRegistry.java:20)
	at com.networknt.consul.ConsulRegistry$ServiceLookupThread.run(ConsulRegistry.java:334)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80)
	... 10 common frames omitted
02:17:38.900 [Thread-3]  INFO  c.n.consul.client.ConsulEcwidClient - no command in serviceName: com.networknt.apib-1.0.0
02:17:38.901 [Thread-3]  INFO  com.networknt.consul.ConsulRegistry - command data not change: serviceName=com.networknt.apib-1.0.0, command=: 
InfluxDbReporter report is called.

```

**Comment by stevehu** [comment]
This is actually not a bug but a normal timeout as the consul client using blocking query on consul agent for a period of time. If there are any change on consul agent services, the query will return immediately with the changes, otherwise, it will timeout and a new query will be sent. This is the way to avoid constantly polling from consul agent.
