### ISSUE TITLE
OpenAPI and GraphQL ValidatorHandlers conflict on config file names

### ISSUE THREAD

**Issue by logi** [networknt/light-4j#252]
Both `com.networknt.openapi.ValidatorHandler` and `com.networknt.graphql.validator.ValidatorHandler` have `CONFIG_NAME = "validator"` so if both are loaded in the same JVM they'll both run
```java
static ValidatorConfig config = (ValidatorConfig)Config.getInstance().getJsonObjectConfig(CONFIG_NAME, ValidatorConfig.class);
```
but with different `ValidatorConfig` classes imported, so the second one to be loaded fails with
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.networknt.handler.Handler.splitClassAndName(Handler.java:262)
        at com.networknt.handler.Handler.initHandlers(Handler.java:214)
        at com.networknt.handler.Handler.<clinit>(Handler.java:38)
        at com.networknt.server.Server.start(Server.java:136)
        at com.networknt.server.Server.main(Server.java:111)
Caused by: java.lang.ClassCastException: com.networknt.graphql.validator.ValidatorConfig cannot be cast to com.networknt.openapi.ValidatorConfig
        at com.networknt.openapi.ValidatorHandler.<clinit>(ValidatorHandler.java:49)
        ... 7 more
```

Currently the content of the two files seems to be compatible, but it would not be surprising if that would also diverge.

**Comment by stevehu** [comment]
Yes. It is great that you bring it up. We never thought we are going to use two or more different frameworks in the same service instance before. At this moment, there are more uses for the light-rest-4j than light-graphql-4j. For this release, maybe we should change the validator.yml for graphql to graphql-validator.yml and change the hybrid framework validator config to hybrid-validator.yml. When we move to 1.6.x release I think we should change the light-rest-4j to rest-validator.yml @ddobrin @logi @NicholasAzar What do you think?

**Comment by logi** [comment]
Sounds reasonable. Perhaps even renaming the REST config as well but with a fallback to the current name and log a deprecation warning?

**Comment by stevehu** [comment]
That is a good idea. Thanks. I will open issues to address them all together.

**Comment by stevehu** [comment]
@logi This has been implemented in light-rest-4j, light-graphql-4j and light-hybrid-4j. Please take a look see if the implementation is expected. Thanks.

**Comment by logi** [comment]
About this comment:
```
# A generic light-4j framework validator configuration. If multiple frameworks are used in the
# same server instance and they have different configurations. You can use openapi-validator.yml
```

If multiple frameworks are used in the same server instance, even if the files are _identical_ then there will be a clas cast exception as the identical config file names are used as the key in the config lookup map and then cast to different config classes.

This means that if two frameworks are used in the same server, since the compiled-in config files are still all called `validator.yml` you must create multiple `foo-validator.yml` files, even if they are identical to the compiled-in files.

**Comment by stevehu** [comment]
Cool. I am not aware of this until now. Thanks for the clarification. I will update the comments accordingly.
