### ISSUE TITLE
Re-starting Server no longer works

### ISSUE THREAD

**Issue by logi** [networknt/light-4j#263]
Unit tests which call `Server.start()` in a `before()` method and `Server.stop()` in an `after()` method have just stopped working.

These tests will succeed with 1.5.17 but with a 1.5.18 built today (15.08.2018) the first will succeed and the second will fail:

```java
public class ServerRestartTest {

    @Test
    public void testStartStop1() {
        Server.start();
        Server.stop();
    }

    @Test
    public void testStartStop2() {
        Server.start();
        Server.stop();
    }

}
```
The exception raised is:
```
java.lang.IllegalStateException: UT000071: Cannot add path template /graphql, matcher already contains an equivalent pattern /graphql

	at io.undertow.util.PathTemplateMatcher.add(PathTemplateMatcher.java:109)
	at io.undertow.util.PathTemplateMatcher.add(PathTemplateMatcher.java:150)
	at com.networknt.handler.Handler.initPaths(Handler.java:119)
	at com.networknt.handler.Handler.init(Handler.java:52)
	at com.networknt.server.Server.start(Server.java:145)
	at is.thing.usernotes.rest.ServerRestartTest.testStartStop2(ServerRestartTest.java:16)
```

**Comment by logi** [comment]
This exact test didn't exist yesterday, but when I last built from develop and ran our unit tests they succeeded.

**Comment by stevehu** [comment]
@logi Thanks for bringing this up. I have reproduced the issue with one of the testing APIs. By checking out the light-example-4j, switching to develop branch, moving to discovery/api_d/http-health and executing mvn clean install, you will see the following error. 

https://github.com/networknt/light-example-4j/tree/develop/discovery/api_d/http-health

```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE!
com.networknt.apid.handler.DataGetHandlerTest  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.IllegalStateException: UT000071: Cannot add path template /v1/data, matcher already contains an equivalent pattern /v1/data
	at io.undertow.util.PathTemplateMatcher.add(PathTemplateMatcher.java:109)
	at io.undertow.util.PathTemplateMatcher.add(PathTemplateMatcher.java:150)
	at com.networknt.handler.Handler.initPaths(Handler.java:119)
	at com.networknt.handler.Handler.init(Handler.java:52)
	at com.networknt.server.Server.start(Server.java:145)
	at com.networknt.apid.handler.TestServer.before(TestServer.java:37)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)

Running com.networknt.apid.handler.HealthGetHandlerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests in error: 
   » IllegalState UT000071: Cannot add path template /v1/data, matcher already c...

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0

```

**Comment by logi** [comment]
I can confirm that my tests now pass.
