### ISSUE TITLE
Consul heartbeat stream limit being exceeded

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#279]
With the latest 1.5.18 release, it seems an issue was introduced where after ~30 minutes the service can no longer issue heartbeats to consul.

On initial deployment the service is registered and appears healthy, then after the following exception the service deregisters (after waiting for the `deregisterAfter` config value amount of time).

Sample `consul.yml`:

```yaml
consulUrl: https://localhost:8443
deregisterAfter: 2m
checkInterval: 30s
tcpCheck: false
httpCheck: false
ttlCheck: true
```

Exception:

```

2018-09-05 23:39:11.351 [pool-3-thread-5] ERROR com.networknt.client.Http2Client - IOException:
--
  | java.io.IOException: UT000184: Stream limit exceeded
  | at io.undertow.protocols.http2.Http2Channel.createStream(Http2Channel.java:890)
  | at io.undertow.client.http2.Http2ClientConnection.sendRequest(Http2ClientConnection.java:173)
  | at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:80)
  | at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:157)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | 2018-09-05 23:39:11.351 [pool-3-thread-5] ERROR c.n.consul.client.ConsulClientImpl - CheckPass request exception
  | java.lang.NullPointerException: null
  | at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:82)
  | at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:157)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)


```

**Comment by stevehu** [comment]
After 1.5.18 release, the right approach to use is the httpCheck. ttlCheck is still unstable and should only be used when services are behind NAT. I will take a look at the issue to fix the ttlCheck. Thanks for bringing it up.

**Comment by stevehu** [comment]
https://doc.networknt.com/tutorial/common/discovery/http-health/

**Comment by stevehu** [comment]
As we are using HTTP/2 with the same connection, once the max number of requests is reached we got this error. Need to re-create the connection on a daily basis.

**Comment by stevehu** [comment]
The max stream id is 2147483647 and it is strange that we have run out this number although each request might have multiple frames and each frame has a stream id. How long has this service instance been running? Thanks.
