### ISSUE TITLE
support default path in handler.yml for single page application

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#316]
I am trying to serve a Single Page Application from light-router and found that we have to define all possible paths the SPA needs. We need to find a better idea to support it. I am thinking about the default path in the definition and wondering if we should support it. 

Here are some of the paths in a react application build. 

```
light-router_1  | 23:55:46.228 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /static/css/main.52395adc.chunk.css.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)
light-router_1  | 23:55:46.230 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /static/js/1.a700ff87.chunk.js.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)
light-router_1  | 23:55:46.231 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /static/js/main.84748456.chunk.js.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)
light-router_1  | 23:55:46.397 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /static/js/1.a700ff87.chunk.js.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)
light-router_1  | 23:55:46.407 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /static/js/main.84748456.chunk.js.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)
light-router_1  | 23:55:46.490 [XNIO-1 I/O-1]   ERROR c.networknt.handler.LightHttpHandler setExchangeStatus - {"statusCode":400,"code":"ERR10016","message":"MISSING_HANDlER","description":"Could not find the handler for the endpoint Method: GET, RequestPath: /favicon.ico.","severity":"ERROR"} at com.networknt.handler.OrchestrationHandler.handleRequest(OrchestrationHandler.java:18)


```

**Comment by miklish** [comment]
The handler code uses Undertow's built in path matcher. If undertow's path matcher supports wildcards, then they should work with the existing implementation.

**Comment by stevehu** [comment]
that is definitely one of the options. However, as most websites will be rendered as root, do we need to have something like /* as default? I tried to comment out the two lines in the following class and so far it is working. We need to find a way to validate the path once the resource handler is in the picture. 

```
public class OrchestrationHandler implements LightHttpHandler {

	static final String MISSING_HANDlER = "ERR10016";

    @Override
    public void handleRequest(HttpServerExchange exchange) throws Exception {
        if (Handler.start(exchange)) {
            Handler.next(exchange);
        } else {
//            String methodPath = String.format("Method: %s, RequestPath: %s", exchange.getRequestMethod(), exchange.getRequestPath());
//            setExchangeStatus(exchange, MISSING_HANDlER, methodPath);
        }
    }
}

```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update resource and handler modules to support light-router serving SPA](https://trello.com/c/cA3gbqaV/17-update-resource-and-handler-modules-to-support-light-router-serving-spa)

**Comment by stevehu** [comment]
https://github.com/networknt/light-router/issues/26
