### ISSUE TITLE
service getting unregistered from consul after a while

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#478]
error on log file:
8:50:05.169 [pool-3-thread-3]   ERROR com.networknt.client.Http2Client$3:597 failed - IOException:
java.io.IOException: UT000184: Stream limit exceeded
       at io.undertow.protocols.http2.Http2Channel.createStream(Http2Channel.java:890)
       at io.undertow.client.http2.Http2ClientConnection.sendRequest(Http2ClientConnection.java:184)
       at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:104)
       at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
18:50:05.170 [pool-3-thread-3]   ERROR c.n.consul.client.ConsulClientImpl:113 checkPass - CheckPass request exception
java.lang.NullPointerException: null
       at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:107)
       at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
18:50:25.168 [pool-3-thread-4]   ERROR com.networknt.client.Http2Client$3:597 failed - IOException:
java.io.IOException: UT000184: Stream limit exceeded
       at io.undertow.protocols.http2.Http2Channel.createStream(Http2Channel.java:890)
       at io.undertow.client.http2.Http2ClientConnection.sendRequest(Http2ClientConnection.java:184)
       at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:104)
       at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
18:50:25.169 [pool-3-thread-4]   ERROR c.n.consul.client.ConsulClientImpl:113 checkPass - CheckPass request exception
java.lang.NullPointerException: null
       at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:107)
       at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)

**Comment by stevehu** [comment]
I have updated the counter to AtomicInteger to avoid multiple thread issue.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service getting unregistered from consul after a while](https://trello.com/c/Ziobho8s/174-service-getting-unregistered-from-consul-after-a-while)
