### ISSUE TITLE
light-4j 1.6.x build fail on Windows environment 

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#609]
run: mvn clean install on windows OS and got error on Server module:

com.networknt.config.ConfigException: "${container.port}" appears in config file cannot be expanded
	at com.networknt.config.ConfigInjection.getValue(ConfigInjection.java:118)
	at com.networknt.config.ConfigInjection.getInjectValue(ConfigInjection.java:67)
	at com.networknt.config.CentralizedManagement.merge(CentralizedManagement.java:60)
	at com.networknt.config.CentralizedManagement.mergeObject(CentralizedManagement.java:43)
	at com.networknt.config.Config$FileConfigImpl.loadSpecificConfigFileAsObject(Config.java:442)
	at com.networknt.config.Config$FileConfigImpl.loadObjectConfig(Config.java:455)
	at com.networknt.config.Config$FileConfigImpl.loadJsonObjectConfigWithSpecificConfigLoader(Config.java:670)
	at com.networknt.config.Config$FileConfigImpl.getJsonObjectConfig(Config.java:239)
	at com.networknt.config.Config$FileConfigImpl.getJsonObjectConfig(Config.java:278)
	at com.networknt.consul.client.ConsulClientImpl.<clinit>(ConsulClientImpl.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)

**Comment by chenyan71** [comment]
the root cause for this issue is  loading config file from resource folder.

In the Junit test resource config folder, it doesn't has consul.yml file. By default, it should load default config file from consul module. 
But we do have a consul.yml in the integration test resource folder which has ${container.port}  injection token:

https://github.com/networknt/light-4j/blob/1.6.x/server/src/integration/resources/config/consul.yml

------
consulUrl: http://localhost:${container.port} 
------

Somehow, in windows, system load the integration test resource folder as class resource folder as well. And the junit test case will use the consul.yml in the integration test resource folder instead of the default file in the consul module.

**Comment by chenyan71** [comment]
add a default consul.yml for test config folder on server module

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [light-4j 1.6.x build fail on Windows environment 1.6.x](https://trello.com/c/Vz5l4ct0/450-light-4j-16x-build-fail-on-windows-environment-16x)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [light-4j 1.6.x build fail on Windows environment master](https://trello.com/c/tJuEmZdw/451-light-4j-16x-build-fail-on-windows-environment-master)
