### ISSUE TITLE
service throws UT005001 once the metrics/influxdb module is enabled

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#613]
One of the users reported that once influxdb is enabled, the following error occurs in the log file even at the time influx access is not happening as the report to influx occurs every 1 or 5 minutes based on the configuration in the metrics.yml 

From the error, it looks like a SSL/TLS issue and we found someone reports a similar issue and their solution at https://github.com/hawkular/hawkular-metrics/commit/3ea7494ac421b00e9756724e59d8752e51b303ac#diff-9b15b8e8890dfe55e0dcfe7fa1fcc0b9

After comparing the code,  we make a change to create the xnio with classloader and everything works without any error. I still don't know the root cause of the issue yet. 

```
2019-09-26 09:37:09.646 EST [Client I/O-6]   ERROR io.undertow.client handleEvent - UT005001: An exception occurred processing the request
java.lang.NullPointerException: null
    at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:709)
    at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
    at org.xnio.conduits.PushBackStreamSourceConduit.read(PushBackStreamSourceConduit.java:52)
    at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
    at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:531)
    at io.undertow.client.http.HttpClientConnection$ClientReadListener.handleEvent(HttpClientConnection.java:516)
    at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
    at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
    at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1175)
    at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
    at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service throws UT005001 once the metrics/influxdb module is enabled master](https://trello.com/c/vcYSMCm4/465-service-throws-ut005001-once-the-metrics-influxdb-module-is-enabled-master)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [service throws UT005001 once the metrics/influxdb module is enabled 1.6.x](https://trello.com/c/8jBTKCua/466-service-throws-ut005001-once-the-metrics-influxdb-module-is-enabled-16x)

**Comment by miklish** [comment]
This error occurs on all https connections from what I understand (not just influxdb).

**Comment by stevehu** [comment]
@miklish I haven't seen this error before. Could you please paste the stacktrace you have and I can compare with the other report to see if they are the same error?

**Comment by miklish** [comment]
I'll ask @jsu216... This was my understanding from discussing with him, but I could be mistaken

**Comment by stevehu** [comment]
I will debug into it once it is reproducible. I understand why the fix works in the hawkular-metrics as it is advised by the Undertow dev team. Our code doesn't have the wrong code in hawkular-metrics but we are using an instance without classloader as a parameter.

**Comment by sjmingdna** [comment]
The problem I ran into had nothing  with the code，that is the Excel default Settings，thanks




------------------ 原始邮件 ------------------
发件人: "Steve Hu"<notifications@github.com>;
发送时间: 2019年10月3日(星期四) 上午8:48
收件人: "networknt/light-4j"<light-4j@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [networknt/light-4j] service throws UT005001 once themetrics/influxdb module is enabled (#613)




I will debug into it once it is reproducible. I understand why the fix works in the hawkular-metrics as it is advised by the Undertow dev team. Our code doesn't have the wrong code in hawkular-metrics but we are using an instance without classloader as a parameter.
