### ISSUE TITLE
microservices sample error

### ISSUE THREAD

**Issue by kasriniv** [networknt/light-4j#65]
The microservices sample of API A-->B-->D and separately calling service C returns an error when service A is invoked. Service B, C, and D invoked separately are fine.
Service A seems to want to access a resource on port 8888 which is not used anywhere..
Here is the stack trace from invoking api A: 0:35:06.119 [XNIO-1 task-1] FfnX3dLFRTmXYt6Pkx2LeA ERROR c.networknt.client.oauth.TokenHelper - IOException: 
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8888 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.networknt.client.oauth.TokenHelper.getToken(TokenHelper.java:68)
	at com.networknt.client.Client.getCCToken(Client.java:291)
	at com.networknt.client.Client.checkCCTokenExpired(Client.java:318)
	at com.networknt.client.Client.populateHeader(Client.java:285)
	at com.networknt.client.Client.propagateHeaders(Client.java:261)
	at io.swagger.handler.DataGetHandler.handleRequest(DataGetHandler.java:36)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:87)
	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:126)
	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:100)
	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:92)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:67)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:62)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 29 common frames omitted
com.networknt.exception.ClientException: IOException: 
	at com.networknt.client.oauth.TokenHelper.getToken(TokenHelper.java:79)
	at com.networknt.client.Client.getCCToken(Client.java:291)
	at com.networknt.client.Client.checkCCTokenExpired(Client.java:318)
	at com.networknt.client.Client.populateHeader(Client.java:285)
	at com.networknt.client.Client.propagateHeaders(Client.java:261)
	at io.swagger.handler.DataGetHandler.handleRequest(DataGetHandler.java:36)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:87)
	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:126)
	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:100)
	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:92)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:67)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:62)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8888 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.networknt.client.oauth.TokenHelper.getToken(TokenHelper.java:68)
	... 19 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 29 more
20:35:06.122 [XNIO-1 task-1] FfnX3dLFRTmXYt6Pkx2LeA ERROR c.n.exception.ExceptionHandler - Exception:
java.lang.Exception: ClientException:
	at io.swagger.handler.DataGetHandler.handleRequest(DataGetHandler.java:66)
	at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
	at com.networknt.validator.ValidatorHandler.handleRequest(ValidatorHandler.java:87)
	at com.networknt.sanitizer.SanitizerHandler.handleRequest(SanitizerHandler.java:87)
	at com.networknt.audit.AuditHandler.handleRequest(AuditHandler.java:126)
	at com.networknt.body.BodyHandler.handleRequest(BodyHandler.java:100)
	at com.networknt.swagger.SwaggerHandler.handleRequest(SwaggerHandler.java:92)
	at com.networknt.correlation.CorrelationHandler.handleRequest(CorrelationHandler.java:67)
	at com.networknt.traceability.TraceabilityHandler.handleRequest(TraceabilityHandler.java:64)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:62)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.networknt.exception.ClientException: IOException: 
	at com.networknt.client.oauth.TokenHelper.getToken(TokenHelper.java:79)
	at com.networknt.client.Client.getCCToken(Client.java:291)
	at com.networknt.client.Client.checkCCTokenExpired(Client.java:318)
	at com.networknt.client.Client.populateHeader(Client.java:285)
	at com.networknt.client.Client.propagateHeaders(Client.java:261)
	at io.swagger.handler.DataGetHandler.handleRequest(DataGetHandler.java:36)
	... 14 common frames omitted
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8888 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.networknt.client.oauth.TokenHelper.getToken(TokenHelper.java:68)
	... 19 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 29 common frames omitted

**Comment by stevehu** [comment]
port 8888 is OAuth2 server so that service to service calls can be protected. The tutorial was a little bit old as the 8888 service as a development edition of the OAuth2 server which is a monolithic in the beginning. 
The new OAuth2 server has 7 microserivces and they can be started in a docker compose with mysql, postgresql and oracle. Are you following a tutorial? which one? These tutorials all need to be upgraded to the latest version of the framework. You can follow the following tutorial and let me know if anything is broken and I can fix them along the way. 

https://networknt.github.io/light-4j/tutorials/microservices/

**Comment by kasriniv** [comment]
I am following the link you mention: https://networknt.github.io/light-4j/tutorials/microservices/
Note that the step I have problems is when the service A is invoked 'before' Oauth2 enabling.
(end of section: 'Configuration')

Found the offending call ..
Client.getInstance().propagateHeaders(request, exchange);
I commented this and the sample works fine.
Perhaps the tutorial can be refreshed to put this line in after OAuth2 enabling.

**Comment by stevehu** [comment]
Thanks for pointing it out. That line is getting the JWT token from OAuth2 server and pass correlationId/traceabilityId to the next service. If security is not enabled, it is not necessary. I will make the change in the tutorial.

**Comment by stevehu** [comment]
This issue actually related to a bug and it is never fixed as all the existing client are working on a security first principal. They have the OAuth2 service setup before building any services. I will get this issue fixed today to make the tutorial transparent to users. Thanks.

https://github.com/networknt/light-4j/issues/40

**Comment by stevehu** [comment]
@kasriniv While updating the tutorials, I am moving some of them to light-rest-4j document site as they are RESTful APIs. We also support graphql and hybrid based on request/response style of microservices as well as messaging based microservices. Let me know if they are any broken links.

**Comment by stevehu** [comment]
@kasriniv I have re-done the tutorial and move it to light-rest-4j site. Here is the link and it works until security is enabled. I will complete the security tomorrow. Thanks for your patience. 

https://networknt.github.io/light-rest-4j/tutorial/microservices/

**Comment by kasriniv** [comment]
Thank you @stevehu ...looking forward to seeing performance numbers before and after Oauth2 enabling..thanks again!

**Comment by stevehu** [comment]
performance numbers with oauth2 enabled is published. 
https://networknt.github.io/light-rest-4j/tutorial/microservices/
