### ISSUE TITLE
double check the tracer has activeSpan in the client header propagation

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#694]
For some reason, there is a chance that the tracer is not null but there is no active span available and we get an NPE.

**Comment by stevehu** [comment]
This is an error that captured on the server. The tracing is on a best effort basis and it shouldn't impact the functionality. 

```
https://38.113.162.52:8441/com.networknt.portal.hybrid.query-1.0.0?group=default.
21:13:13.657 [XNIO-1 I/O-4]   ERROR n.lightapi.portal.HybridQueryClient getUserByEmail - Exception:
java.lang.NullPointerException: null
	at io.opentracing.tag.StringTag.set(StringTag.java:25)
	at com.networknt.client.Http2Client.addAuthTokenTrace(Http2Client.java:380)
	at com.networknt.client.Http2Client.populateHeader(Http2Client.java:498)
	at com.networknt.client.Http2Client.propagateHeaders(Http2Client.java:436)
	at net.lightapi.portal.HybridQueryClient.getUserByEmail(HybridQueryClient.java:86)
	at net.lightapi.portal.covid.command.handler.CreateEntity.handle(CreateEntity.java:44)
	at com.networknt.rpc.router.JsonHandler.processRequest(JsonHandler.java:83)
	at com.networknt.rpc.router.JsonHandler.lambda$handleRequest$0(JsonHandler.java:45)
	at io.undertow.io.AsyncReceiverImpl$2$1.handleRequest(AsyncReceiverImpl.java:162)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.io.AsyncReceiverImpl$2.handleEvent(AsyncReceiverImpl.java:159)
	at io.undertow.io.AsyncReceiverImpl$2.handleEvent(AsyncReceiverImpl.java:143)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.channels.DetachableStreamSourceChannel$SetterDelegatingListener.handleEvent(DetachableStreamSourceChannel.java:231)
	at io.undertow.channels.DetachableStreamSourceChannel$SetterDelegatingListener.handleEvent(DetachableStreamSourceChannel.java:218)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.conduits.StreamSourceChannelWrappingConduit$1.handleEvent(StreamSourceChannelWrappingConduit.java:85)
	at org.xnio.conduits.StreamSourceChannelWrappingConduit$1.handleEvent(StreamSourceChannelWrappingConduit.java:83)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedStreamSourceChannel$1.run(AbstractFramedStreamSourceChannel.java:282)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$1.run(AbstractFramedChannel.java:143)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
21:13:13.663 [XNIO-1 I/O-4]   ERROR com.networknt.rpc.Handler getStatus - {"statusCode":400,"code":"ERR10014","message":"GENERIC_EXCEPTION","description":"Generic Exception 
```
