### ISSUE TITLE
switch toByteBuffer from direct to indirect

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#707]
The UTF8 string length is not predictable and the performance gain is unknown. To avoid issues like below, switch to wrap instead. 

```
12:55:36.148 [XNIO-1 task-154]   ERROR c.n.exception.ExceptionHandler handleRequest - Exception:
java.nio.BufferOverflowException: null
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:410)
	at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:906)
	at com.networknt.utility.NioUtils.toByteBuffer(NioUtils.java:253)
	at net.lightapi.portal.covid.query.handler.GetWebsiteByEmail.handle(GetWebsiteByEmail.java:49)
	at com.networknt.rpc.router.JsonHandler.processRequest(JsonHandler.java:88)
	at com.networknt.rpc.router.JsonHandler.handleRequest(JsonHandler.java:56)
	at com.networknt.handler.Handler.next(Handler.java:208)
	at com.networknt.handler.Handler.next(Handler.java:229)
	at com.networknt.cors.CorsHttpHandler.handleRequest(CorsHttpHandler.java:74)
	at com.networknt.handler.Handler.next(Handler.java:208)
	at com.networknt.handler.Handler.next(Handler.java:229)
	at com.networknt.jaeger.tracing.JaegerHandler.handleRequest(JaegerHandler.java:123)
	at com.networknt.handler.Handler.next(Handler.java:208)
	at com.networknt.handler.Handler.next(Handler.java:229)
	at com.networknt.exception.ExceptionHandler.handleRequest(ExceptionHandler.java:76)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [switch toByteBuffer from direct to indirect](https://trello.com/c/OsvVikBS/661-switch-tobytebuffer-from-direct-to-indirect)
