### ISSUE TITLE
When maxTransferFileSize is set, the server fails to start.

### ISSUE THREAD

**Issue by thirtysixmm** [networknt/light-4j#887]
If maxTransferFileSize value is set in the server.yml file, the server fails to start with the following exception.

```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.networknt.server.ServerOption.setServerOption(ServerOption.java:102)
	at com.networknt.server.ServerOption.serverOptionInit(ServerOption.java:47)
	at com.networknt.server.Server.serverOptionInit(Server.java:237)
	at com.networknt.server.Server.bind(Server.java:265)
	... 3 common frames omitted
```

**Comment by thirtysixmm** [comment]
Created a PR to fix this issue. https://github.com/networknt/light-4j/pull/888

**Comment by stevehu** [comment]
The behaviour I have is that the server is not started due to cannot bind to port 8443. The root cause is the above error though. Thanks a lot for raising the issue and getting it fixed.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When maxTransferFileSize is set, the server fails to start. light-4j master](https://trello.com/c/fYwPnb9S/912-when-maxtransferfilesize-is-set-the-server-fails-to-start-light-4j-master)
